[project]
name = "ems-ota-manager"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "cryptography>=46.0.5",
    "ems-common",
    "httpx>=0.28.1",
    "jsonschema>=4.26.0",
    "pyyaml>=6.0.3",
    "pyzmq>=27.1.0",
]

[tool.uv.sources]
ems-common = { workspace = true }

[build-system]
requires = ["uv_build>=0.10,<0.11"]
build-backend = "uv_build"
