# ems-certs_0.1.0.bb — EMS per-device mTLS certificates
#
# Installs device-specific mTLS certificates into /etc/ems/certs/ for
# cloud_manager MQTT/TLS authentication.
#
# IMPORTANT: Cert files MUST be generated per-device before running bitbake.
# Run tools/gen-device-cert.sh and place the output in a directory, then set
# FILESEXTRAPATHS in your machine conf or local.conf to point to that directory:
#
#   FILESEXTRAPATHS:prepend:pn-ems-certs := "/path/to/device/certs:"
#
# Security notes:
#   - CA private key MUST NOT be included — only ca.crt (public cert for
#     broker trust), device.crt, and device.key.
#   - device.key is installed 0600 (owner read/write only).
#   - Files are owned by ems:ems — ensure the ems user exists in the image
#     (created by ems-users recipe or base-passwd customization).

SUMMARY = "EMS device mTLS certificates"
DESCRIPTION = "Per-device TLS certificates for MQTT cloud authentication. \
Baked into the image at build time from certs generated by tools/gen-device-cert.sh."
LICENSE = "CLOSED"

# Source files are generated externally by tools/gen-device-cert.sh.
# Place ca.crt, device.crt, and device.key in a directory and set
# FILESEXTRAPATHS:prepend:pn-ems-certs to that directory path.
SRC_URI = " \
    file://ca.crt \
    file://device.crt \
    file://device.key \
"

# No compilation required — this is a FILES recipe.
do_configure[noexec] = "1"
do_compile[noexec] = "1"

do_install() {
    # Create the certificate directory in the image rootfs
    install -d ${D}/etc/ems/certs

    # Install public certificates (0644 — readable by all, writable by owner)
    install -m 0644 ${WORKDIR}/ca.crt ${D}/etc/ems/certs/ca.crt
    install -m 0644 ${WORKDIR}/device.crt ${D}/etc/ems/certs/device.crt

    # Install private key (0600 — owner read/write only, never world-readable)
    install -m 0600 ${WORKDIR}/device.key ${D}/etc/ems/certs/device.key
}

# Package the certificate directory
FILES:${PN} = "/etc/ems/certs/*"

# The ems user must exist before cert files are owned (post-install hook or
# base image user creation handles this — see ems-users or base-passwd).
# For rootfs ordering, ems-certs should come after ems-users if it exists.
RDEPENDS:${PN} = ""
