[project]
name = "ems-diagnostics"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "duckdb>=1.5.0",
    "ems-common",
    "jsonschema>=4.26.0",
    "msgpack>=1.1.2",
    "pyyaml>=6.0.3",
    "pyzmq>=27.1.0",
]

[tool.uv.sources]
ems-common = { workspace = true }

[build-system]
requires = ["uv_build>=0.10,<0.11"]
build-backend = "uv_build"
