[project]
name = "ems-scheduler"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "ems-common",
    "pyzmq>=26.2.1",
    "msgpack>=1.1.0",
    "pyyaml>=6.0.2",
    "jsonschema>=4.23.0",
]

[tool.uv.sources]
ems-common = { workspace = true }

[build-system]
requires = ["uv_build>=0.10,<0.11"]
build-backend = "uv_build"
